
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author student
 */
public class Shop extends javax.swing.JFrame {
    static String memid;        //要宣告成static，否則main不能用
    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        red = new javax.swing.JRadioButton();
        green = new javax.swing.JRadioButton();
        wulon = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        size = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sugar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pearl = new javax.swing.JCheckBox();
        pei = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        no = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        jLabel1.setText("飲品");

        buttonGroup1.add(red);
        red.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        red.setSelected(true);
        red.setText("紅茶");

        buttonGroup1.add(green);
        green.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        green.setText("綠茶");

        buttonGroup1.add(wulon);
        wulon.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        wulon.setText("烏龍茶");

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        jLabel2.setText("杯量");

        size.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "大杯", "中杯", "小杯" }));

        jLabel3.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        jLabel3.setText("甜度");

        sugar.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        sugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "無糖", "半糖", "夭壽甜" }));

        jLabel4.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        jLabel4.setText("加料");

        pearl.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        pearl.setText("珍珠");

        pei.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        pei.setText("胚芽");

        jButton1.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        jButton1.setText("確定");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        jLabel5.setText("數量");

        no.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        no.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButton2.setFont(new java.awt.Font("微軟正黑體", 1, 24)); // NOI18N
        jButton2.setText("清除");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(red)
                                .addGap(10, 10, 10)
                                .addComponent(green)
                                .addGap(16, 16, 16)
                                .addComponent(wulon))
                            .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(pearl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pei))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(red)
                    .addComponent(green)
                    .addComponent(wulon))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pearl)
                    .addComponent(pei))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(no))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s1 = "";
        if (red.isSelected()) {
            s1 = "紅茶";
        }
        if (green.isSelected()) {
            s1 = "綠茶";
        }
        if (wulon.isSelected()) {
            s1 = "烏龍茶";
        }

        String s2 = (String) size.getSelectedItem();
        String s3 = (String) sugar.getSelectedItem();
        String s4 = "";
        if (pearl.isSelected()) {
            s4 += "珍珠 ";
        }
        if (pei.isSelected()) {
            s4 += "胚芽";
        }

        int num = (int) no.getValue();

        //======== DB連線 ==================
        String driver = "com.mysql.jdbc.Driver";
        String url = "jdbc:mysql://localhost:3306/test";
        String user = "root", password = "1234";

        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, password);

            if (con != null && !con.isClosed()) {
                Statement st = con.createStatement();
                String s = "INSERT INTO shop(id, type, size, sugar, other, no) VALUES(?,?,?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(s);
                ps.setString(1, memid);
                ps.setNString(2, s1);  // setNString 可以寫入中文，否則寫入到時資料庫會變?
                ps.setNString(3, s2);
                ps.setNString(4, s3);
                ps.setNString(5, s4);
                ps.setInt(6, num);  
                                
                String order = "訂單內容：" + s1 + s2 + s3 + s4 + num + "杯?";
                int n = JOptionPane.showConfirmDialog(null, order, "Login", JOptionPane.YES_NO_OPTION);
                if(n == 0){
                    ps.executeUpdate();
                }
                
            }
            con.close();
        } 
        catch (Exception x) {
            System.out.println(x);
        }
        //==================================
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        red.setSelected(true);
        size.setSelectedItem("大杯");
        sugar.setSelectedItem("無糖");
        pearl.setSelected(false);
        pei.setSelected(false);
        no.setValue(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        memid = args[0]; // 用來接收Frame傳過來的參數
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton green;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner no;
    private javax.swing.JCheckBox pearl;
    private javax.swing.JCheckBox pei;
    private javax.swing.JRadioButton red;
    private javax.swing.JComboBox<String> size;
    private javax.swing.JComboBox<String> sugar;
    private javax.swing.JRadioButton wulon;
    // End of variables declaration//GEN-END:variables
}
